modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"

[[mods]]
modId="toolbelt"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.toolbelt]]
   modId="neoforge"
   type="required"
   versionRange="[20.4.72-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.4,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="sewingkit"
   type="optional"
   versionRange="[1.8.5,)"
   ordering="NONE"
   side="BOTH"